### ISSUE TITLE
Change Map component zoom from static to prop

### ISSUE THREAD

**Issue by bearcanrun** [NomadGraphix/google-react-maps#2]
Just implementing functionality you already had available! Pull request here: #1 

PS: This is a really awesome implementation of google maps for react! I've been struggling with problem after problem with the [mainstream repo](http://react-google-maps.tomchentw.com/). I was just about shift to leaflet, when I came across your repo from a Google Search. I'm still a react noob, but I'll do my best to help out if I can. I don't mind evangelizing either if you're comfortable about pushing it out into the world.

**Comment by NomadGraphix** [comment]
Thanks! I appreciate the compliment. It's my first serious GitHub react project. I'd like to keep it going since I'm using it all the time.

**Comment by NomadGraphix** [comment]
That's to say, go ahead and help out if you'd like. I'd be happy for the help with the project.
