### ISSUE TITLE
Doesn't play nice with React 16

### ISSUE THREAD

**Issue by mihailp** [NomadGraphix/google-react-maps#7]
Just updated to React 16.0.0 and got this error:

`Uncaught Error: Element ref was specified as a string (map) but no owner was set. You may have multiple copies of React loaded.`

My wild guess is this is because **google-react-maps** has a dependency of react 15 and probably both versions are used. When I execute `npm ls react` it shows:

```
google-react-maps@1.2.15
│ └── react@15.6.2
```

**Comment by mihailp** [comment]
P.S. Also PropTypes in React 16 is deprecated now.

**Comment by NomadGraphix** [comment]
You're right, we need to remove google-react-maps from the dependency tree. Let me check into this, but you are welcome to submit a pull request.

**Comment by NomadGraphix** [comment]
Made adjustments for react 16. I think there may still be issues with server-side rendering that do not break it, but will throw warnings.
